# Networks
networks:
  csm-network:
    driver: bridge
    external: true

# Volumes
volumes:
  csm-postgres-data:
    name: kScfWrF8PUtK0e9FdGtB
  csm-test-postgres-data:
    name: tScfWrF8pUtiK0e9FaGatB
  csm-redis-data:
    name: 4TWaJPJdILWuVDQ6Nctz

# Services
services:

  # Redis for queues, sync states, caching
  csm-redis:
    image: redis:8.0
    container_name: csm-redis
    ports:
      - '6379:6379'
    command: ["redis-server", "--requirepass", "supersecretpassword"]
    volumes:
      - csm-redis-data:/data
    networks:
      - csm-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "supersecretpassword", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # PostgreSQL for event store, materialized views, rules, transactions
  csm-postgres:
    image: postgres:17.4
    container_name: csm-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: csm
      POSTGRES_USER: csm_user
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - csm-postgres-data:/var/lib/postgresql/data
    networks:
      - csm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U csm_user -d csm"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Database Service for Tests
  csm-test-postgres:
    image: postgres:17.4
    container_name: csm-test-postgres
    ports:
      # Map to a different host port (e.g., 5433) to avoid conflict 
      - '5433:5432'
    environment:
      # Use a dedicated database name for testing
      POSTGRES_DB: csm_test 
      POSTGRES_USER: csm_user_test
      POSTGRES_PASSWORD: supersecretpassword_test
    volumes:
      # Use a dedicated volume for test data
      - csm-test-postgres-data:/var/lib/postgresql/data
    networks:
      - csm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U csm_user_test -d csm_test"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Laravel + Nginx API server
  csm-api:
    container_name: csm-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "8080:8080"
    volumes:
      - './html/:/var/www/html'
    environment:
      # SSL_MODE: "full"
      PHP_OPCACHE_ENABLE: "1"
    networks:
      - csm-network
    depends_on:
      - csm-postgres
      - csm-redis
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8080/v1' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # Redis Insight for managing Redis data
  csm-redis-insight:
    image: redis/redisinsight
    container_name: redis-insight
    ports:
      - '5540:5540'  # Redis Insight default port
    networks:
      - csm-network
    environment:
      REDIS_PORT: 6379  
      REDIS_PASS: supersecretpassword  # Password for Redis
    restart: unless-stopped

